//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlocklyMirai.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlocklyMirai.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;debug&quot;: false, &quot;core_version&quot;: &quot;2.8.0-RC&quot;, &quot;console_version&quot;: &quot;2.8.0-RC&quot;, &quot;build_cmd&quot;: &quot;gradlew build -i&quot;} 的本地化字符串。
        /// </summary>
        internal static string DefaultConfig {
            get {
                return ResourceManager.GetString("DefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;style&gt;.loading {  position: fixed;  z-index: 1919810;  left: 0px;  top: 0px;  width: 100%;  height: 100%;  background: #EEE;  text-align: center;}.loading-content {  position: absolute;  top: 50%;  left: 50%;  width: 300px;  height: 100px;  margin-top: -50px;  margin-left: -150px;  text-align: center;}.loading-content&gt;.logo{  width: 300px;  height: 50px;  margin: 0 auto;}.logo {  width: 216px;  height: 36px;  background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultHtml {
            get {
                return ResourceManager.GetString("DefaultHtml", resourceCulture);
            }
        }
    }
}
